local opt = vim.opt

opt.number = true
opt.relativenumber = true
opt.tabstop = 2
opt.shiftwidth = 2
opt.expandtab = true
opt.smartindent = true
opt.wrap = false
opt.swapfile = false
opt.backup = false
opt.undofile = true
opt.undodir = vim.fn.stdpath("data") .. "/undo"
opt.hlsearch = false
opt.incsearch = true
opt.termguicolors = true
opt.scrolloff = 8
opt.sidescrolloff = 8
opt.signcolumn = "yes"
opt.updatetime = 250
opt.timeoutlen = 300
opt.splitright = true
opt.splitbelow = true
opt.cursorline = true
opt.mouse = "a"
opt.clipboard = "unnamedplus"
opt.completeopt = "menuone,noinsert,noselect"
opt.pumheight = 10
opt.showmode = false
opt.laststatus = 3
opt.fileencoding = "utf-8"
opt.ignorecase = true
opt.smartcase = true
opt.list = true
opt.listchars = { tab = "» ", trail = "·", nbsp = "␣" }
